# Generated by Django 4.0.3 on 2022-04-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Ania Dev', max_length=255),
        ),
    ]
